# Generated by Django 5.0.4 on 2024-04-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatafile',
            name='format',
        ),
        migrations.RemoveField(
            model_name='metadatafile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='metadatafile',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='metadatafile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='metadatafile',
            name='width',
        ),
    ]
